output:
  - ASW
  - ACB
  - CLM
  - MXL
  - PUR

pops:
  ASW:
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/CEU_hg38.txt
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/YRI_hg38.txt
  ACB:
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/CEU_hg38.txt
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/YRI_hg38.txt
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/PEL_hg38.txt
  CLM:
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/CEU_hg38.txt
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/YRI_hg38.txt
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/PEL_hg38.txt
  MXL:
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/CEU_hg38.txt
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/YRI_hg38.txt
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/PEL_hg38.txt
  PUR:
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/CEU_hg38.txt
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/YRI_hg38.txt
    - /project/jazlynmo_738/DataRepository/Human/1000GenomeNYGC_hg38/FileInformation/pops/PEL_hg38.txt

chroms: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
